# Generated by Django 5.1.1 on 2024-09-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="posts",
                to="posts.tag",
            ),
        ),
    ]
