# Generated by Django 5.1.1 on 2024-10-15 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_post_tags"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="author",
            new_name="user",
        ),
    ]
