# Generated by Django 5.1.1 on 2024-10-15 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_rename_author_comment_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="user",
            new_name="author",
        ),
    ]
