services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: snap-share
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/root
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=snap-share
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env

volumes:
  postgres_data:
