name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
      
    - name: Build and run Docker containers
      run: |
        docker-compose up -d --build
        docker-compose run web python manage.py test

    - name: Stop and remove Docker containers
      if: always()
      run: |
        docker-compose down
